// Rize okulları - başvuru formu okul listesi
export const RIZE_OKULLARI: string[] = [
  "RİZE - ARDEŞEN - Alparslan Ortaokulu",
  "RİZE - ARDEŞEN - Ardeşen Anadolu İmam Hatip Lisesi",
  "RİZE - ARDEŞEN - Ardeşen Fırtına Vadisi İrfan Tufan Karaoğlu Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - ARDEŞEN - Ardeşen İmam Hatip Ortaokulu",
  "RİZE - ARDEŞEN - Ardeşen Lokman Hekim Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - ARDEŞEN - Ardeşen Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - ARDEŞEN - ARDEŞEN NECİP FAZIL KISAKÜREK İMAM HATİP ORTAOKULU",
  "RİZE - ARDEŞEN - Ardeşen Piri Reis Denizcilik Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - ARDEŞEN - Ardeşen Şehit Ömer Halisdemir Fen Lisesi",
  "RİZE - ARDEŞEN - Işıklı 60 Yıl Ortaokulu",
  "RİZE - ARDEŞEN - Köprüköy Ortaokulu",
  "RİZE - ARDEŞEN - RABİA HATUN KIZ ANADOLU İMAM HATİP LİSESİ",
  "RİZE - ARDEŞEN - Seslıkaya Ziya Okutan Ortaokulu",
  "RİZE - ARDEŞEN - Türk Telekom Kanuni Anadolu Lisesi",
  "RİZE - ARDEŞEN - Yavuz Selim Ortaokulu",
  "RİZE - ARDEŞEN - Ardeşen Cumhuriyet İlkokulu",
  "RİZE - ARDEŞEN - Ardeşen Merkez Fatih İlkokulu",
  "RİZE - ARDEŞEN - Seslıkaya Ziya Okutan İlkokulu",
  "RİZE - ARDEŞEN - Fikri Keçeli İlkokulu",
  "RİZE - ARDEŞEN - Ardeşen Fatih İlkokulu",
  "RİZE - ARDEŞEN - Atatürk Anaokulu",
  "RİZE - ARDEŞEN - Borsa İstanbul İlkokulu",
  "RİZE - ARDEŞEN - Cumhuriyet İlkokulu",
  "RİZE - ARDEŞEN - Gazi Mustafa Kemal İlkokulu",
  "RİZE - ARDEŞEN - Işıklı 60 Yıl İlkokulu",
  "RİZE - ARDEŞEN - Köprüköy İlkokulu",
  "RİZE - ARDEŞEN - Mesut Karaoğlu İlkokulu",
  "RİZE - ÇAMLIHEMŞİN - Atatürk Ortaokulu",
  "RİZE - ÇAMLIHEMŞİN - Çamlıhemşin Anadolu İmam Hatip Lisesi",
  "RİZE - ÇAMLIHEMŞİN - Çamlıhemşin Çok Programlı Anadolu Lisesi",
  "RİZE - ÇAMLIHEMŞİN - DİKKAYA ORTAOKULU",
  "RİZE - ÇAMLIHEMŞİN - İstanbul Ticaret Odası Şehit Binbaşı Ömer Aktuğ Ortaokulu",
  "RİZE - ÇAMLIHEMŞİN - ATATÜRK İLKOKULU",
  "RİZE - ÇAMLIHEMŞİN - DİKKAYA İLKOKULU",
  "RİZE - ÇAMLIHEMŞİN - Düzmahalle İlkokulu",
  "RİZE - ÇAMLIHEMŞİN - İstanbul Ticaret Odası Şehit Binbaşı Ömer Aktuğ İlkokulu",
  "RİZE - ÇAYELİ - Ahmet Hamdi-Nurzan İshakoğlu Anadolu Lisesi",
  "RİZE - ÇAYELİ - Beyazsu Ortaokulu",
  "RİZE - ÇAYELİ - Büyükköy Ortaokulu",
  "RİZE - ÇAYELİ - Çayeli Ahmet Hamdi İshakoğlu Denizcilik Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - ÇAYELİ - Çayeli Anadolu İmam Hatip Lisesi",
  "RİZE - ÇAYELİ - Çayeli Anadolu Lisesi",
  "RİZE - ÇAYELİ - Çayeli Barbaros Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - ÇAYELİ - Çayeli Fen Lisesi",
  "RİZE - ÇAYELİ - Çayeli Hacı Ahmet Hamdi İshakoğlu Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - ÇAYELİ - Çayeli Halk Eğitimi Merkezi",
  "RİZE - ÇAYELİ - Çayeli Kız Anadolu İmam Hatip Lisesi",
  "RİZE - ÇAYELİ - Çayeli Kız Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - ÇAYELİ - Hüseyin Rüştü Altunbaş Ortaokulu",
  "RİZE - ÇAYELİ - Kaptanpaşa İzzet Akcal Yatılı Bölge Ortaokulu",
  "RİZE - ÇAYELİ - Madenli Ortaokulu",
  "RİZE - ÇAYELİ - Merkez Atatürk Ortaokulu",
  "RİZE - ÇAYELİ - Şehit Muhammet Ambar İmam Hatip Ortaokulu",
  "RİZE - ÇAYELİ - Yamantürk Ortaokulu",
  "RİZE - ÇAYELİ - Çayeli Yamaç İlkokulu",
  "RİZE - ÇAYELİ - Hasan Yılmaz İlkokulu",
  "RİZE - ÇAYELİ - Çayeli Beyazsu İlkokulu",
  "RİZE - ÇAYELİ - 9 Mart İlkokulu",
  "RİZE - ÇAYELİ - Tunca Şehit Cumalı Ayçiçek İlkokulu",
  "RİZE - ÇAYELİ - Fikri Keçeli İlkokulu",
  "RİZE - ÇAYELİ - Beyazsu İlkokulu",
  "RİZE - ÇAYELİ - Büyükköy İlkokulu",
  "RİZE - ÇAYELİ - İshakoğlu İlkokulu",
  "RİZE - ÇAYELİ - Kaptanoğlu İlkokulu",
  "RİZE - ÇAYELİ - Kaptanpaşa İzzet Akçal İlkokulu",
  "RİZE - ÇAYELİ - Madenli ilkokulu",
  "RİZE - DEREPAZARI - Adem Özdemir Anadolu Lisesi",
  "RİZE - DEREPAZARI - Ali Rıza Yılmaz Ortaokulu",
  "RİZE - DEREPAZARI - DEREPAZARI İMAM HATİP ORTAOKULU",
  "RİZE - DEREPAZARI - Derepazarı Merkez İlkokulu",
  "RİZE - DEREPAZARI - Fıçıcılar İlkokulu",
  "RİZE - FINDIKLI - Aksu Atatürk Ortaokulu",
  "RİZE - FINDIKLI - Arılı Ortaokulu",
  "RİZE - FINDIKLI - Çağlayan Osman Hacıalioğlu Ortaokulu",
  "RİZE - FINDIKLI - Fındıklı 15 Temmuz Şehitleri Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - FINDIKLI - Fındıklı TOBB Anadolu İmam Hatip Lisesi",
  "RİZE - FINDIKLI - İbn-i Sina Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - FINDIKLI - Muammer Çiçekoğlu Ortaokulu",
  "RİZE - FINDIKLI - 11 Mart İlkokulu",
  "RİZE - FINDIKLI - Aksu Atatürk İlkokulu",
  "RİZE - FINDIKLI - Arılı İlkokulu",
  "RİZE - FINDIKLI - Çağlayan Osman Hacıalioğlu İlkokulu",
  "RİZE - FINDIKLI - FINDIKLI İLKOKULU",
  "RİZE - FINDIKLI - Sümer İlkokulu",
  "RİZE - GÜNEYSU - Osman Erkan Kız Anadolu İmam Hatip Lisesi",
  "RİZE - GÜNEYSU - Borsa İstanbul Ortaokulu",
  "RİZE - GÜNEYSU - Güneysu Şehit Kemal Mutlu Fen Lisesi",
  "RİZE - GÜNEYSU - Güneysu Spor Lisesi",
  "RİZE - GÜNEYSU - Kaptan Ahmet Erdoğan Anadolu İmam Hatip Lisesi",
  "RİZE - GÜNEYSU - Güneysu İmam Hatip Ortaokulu",
  "RİZE - GÜNEYSU - Güneysu Anadolu Lisesi",
  "RİZE - GÜNEYSU - Adacami İlkokulu",
  "RİZE - GÜNEYSU - ÖZEL BİLGE İLKOKULU",
  "RİZE - GÜNEYSU - ÖZEL GÜNEYSU OKULLARI İLKOKULU",
  "RİZE - GÜNEYSU - ÖZEL GÜNEYSU OKULLARI ORTAOKULU",
  "RİZE - GÜNEYSU - Güneysu İlkokulu",
  "RİZE - GÜNEYSU - Kıbledağı Şehit Metin Çetin İlkokulu",
  "RİZE - GÜNEYSU - Ulucami İlkokulu",
  "RİZE - HEMŞİN - MERKEZ ORTAOKULU",
  "RİZE - HEMŞİN - Hemşin Çok Programlı Anadolu Lisesi",
  "RİZE - HEMŞİN - MERKEZ İLKOKULU",
  "RİZE - İKİZDERE - İkizdere Anadolu İmam Hatip Lisesi",
  "RİZE - İKİZDERE - ATATÜRK ORTAOKULU",
  "RİZE - İKİZDERE - Fazliye Hüseyin Turanlı Çok Programlı Anadolu Lisesi",
  "RİZE - İKİZDERE - ATATÜRK İLKOKULU",
  "RİZE - İYİDERE - Merkez Ortaokulu",
  "RİZE - İYİDERE - Çiftlik Ortaokulu",
  "RİZE - İYİDERE - Hazar Çaysan Ortaokulu",
  "RİZE - İYİDERE - İyidere Anadolu Lisesi",
  "RİZE - İYİDERE - İyidere İmam Hatip Ortaokulu",
  "RİZE - İYİDERE - İYİDERE MESLEKİ VE TEKNİK ANADOLU LİSESİ",
  "RİZE - İYİDERE - Büyükçiftlik İlkokulu",
  "RİZE - İYİDERE - Hazar Çaysan İlkokulu",
  "RİZE - İYİDERE - Merkez İlkokulu",
  "RİZE - KALKANDERE - Kalkandere Anadolu İmam Hatip Lisesi",
  "RİZE - KALKANDERE - Şehit Fikret Metin Öztürk Çok Programlı Anadolu Lisesi",
  "RİZE - KALKANDERE - ORMANLI ORTAOKULU",
  "RİZE - KALKANDERE - YOLBAŞI ORTAOKULU",
  "RİZE - KALKANDERE - ÇAYIRLI ORTAOKULU",
  "RİZE - KALKANDERE - ATATÜRK ORTAOKULU",
  "RİZE - KALKANDERE - DAĞDİBİ ORTAOKULU",
  "RİZE - KALKANDERE - ATATÜRK İLKOKULU",
  "RİZE - KALKANDERE - ÇAYIRLI İLKOKULU",
  "RİZE - KALKANDERE - DAĞDİBİ İLKOKULU",
  "RİZE - KALKANDERE - ORMANLI İLKOKULU",
  "RİZE - KALKANDERE - YOLBAŞI İLKOKULU",
  "RİZE - MERKEZ - Ambarlık Ortaokulu",
  "RİZE - MERKEZ - Gülbahar Hatun Kız Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - MERKEZ - Ekrem Orhon Turizm Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - MERKEZ - Elmalı Ortaokulu",
  "RİZE - MERKEZ - Kendirli Şehit Azim ÖZDEMİR Ortaokulu",
  "RİZE - MERKEZ - Merkez Atatürk Ortaokulu",
  "RİZE - MERKEZ - Rize Türkiye Odalar ve Borsalar Birliği Fen Lisesi",
  "RİZE - MERKEZ - Rize Sosyal Bilimler Lisesi",
  "RİZE - MERKEZ - Tevfik İleri Anadolu Lisesi",
  "RİZE - MERKEZ - Tevfik İleri Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - MERKEZ - Rize Merkez Ticaret Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - MERKEZ - Rize Anadolu Lisesi",
  "RİZE - MERKEZ - Rize Anadolu İmam Hatip Lisesi",
  "RİZE - MERKEZ - Taşlıdere Gazi Ortaokulu",
  "RİZE - MERKEZ - Ömer Halaç İşitme Engelliler Ortaokulu",
  "RİZE - MERKEZ - Veliköy Uzun Mustafa Kopuz Ortaokulu",
  "RİZE - MERKEZ - Kasarcılar Ortaokulu",
  "RİZE - MERKEZ - Hasan Kemal Yardımcı Denizcilik Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - MERKEZ - Kömürcüler Ortaokulu",
  "RİZE - MERKEZ - Çaykur Ortaokulu",
  "RİZE - MERKEZ - Reşadiye Zihni Derin Ortaokulu",
  "RİZE - MERKEZ - Şehit Nedim ÇALIK Ortaokulu",
  "RİZE - MERKEZ - Fatih Anadolu Lisesi",
  "RİZE - MERKEZ - Mehmet Akif Ersoy Ortaokulu",
  "RİZE - MERKEZ - Ali Metin Kazancı Rize Lisesi",
  "RİZE - MERKEZ - Şehit Murat Çalışkaner İmam Hatip Ortaokulu",
  "RİZE - MERKEZ - Karasu Ortaokulu",
  "RİZE - MERKEZ - Çay Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - MERKEZ - 100. Yıl Cumhuriyet Ortaokulu",
  "RİZE - MERKEZ - Rize İmam Hatip Ortaokulu",
  "RİZE - MERKEZ - Kendirli Şehit Soner Fazlıoğlu Anadolu İmam Hatip Lisesi",
  "RİZE - MERKEZ - Ortapazar Ortaokulu",
  "RİZE - MERKEZ - Hüseyin Yardımcı Ortaokulu",
  "RİZE - MERKEZ - Rize Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - MERKEZ - Dörtyol Şehit Halil Sadıkoğlu Ortaokulu",
  "RİZE - MERKEZ - Pazarköy Hafız Ali Usta Ortaokulu",
  "RİZE - MERKEZ - Mahmut Celalettin ÖKTEN İmam Hatip Ortaokulu",
  "RİZE - MERKEZ - Hasan Sağır İmam Hatip Ortaokulu",
  "RİZE - MERKEZ - Şehit Onur Kılıç Kız Anadolu İmam Hatip Lisesi",
  "RİZE - MERKEZ - Şehit Erhan Dural Kız Anadolu İmam Hatip Lisesi",
  "RİZE - MERKEZ - FATİH ORTAOKULU",
  "RİZE - MERKEZ - BOĞAZ ORTAOKULU",
  "RİZE - MERKEZ - Küçükçayır Ortaokulu",
  "RİZE - MERKEZ - Gündoğdu 29 Ekim Ortaokulu",
  "RİZE - MERKEZ - Ömer Halaç Özel Eğitim Meslek Lisesi",
  "RİZE - MERKEZ - Nuri Pakdil İmam Hatip Ortaokulu",
  "RİZE - MERKEZ - AMBARLIK İLKOKULU",
  "RİZE - MERKEZ - ZİYA GÖKALP İLKOKULU",
  "RİZE - MERKEZ - METİN BOSTANCIOGLU İLKOKULU",
  "RİZE - MERKEZ - PETROL OFİSİ İLKOKULU",
  "RİZE - MERKEZ - MEHMETÇİK İLKOKULU",
  "RİZE - MERKEZ - VAKIFBANK İLKOKULU",
  "RİZE - MERKEZ - Kurtuluş İlkokulu",
  "RİZE - MERKEZ - Türkiye Odalar ve Borsalar Birliği İlkokulu",
  "RİZE - MERKEZ - Doğuşçay İlkokulu",
  "RİZE - MERKEZ - Çay İlkokulu",
  "RİZE - MERKEZ - ÖZEL RİZE ANADOLU İLKOKULU",
  "RİZE - MERKEZ - ÖZEL RİZE ANADOLU ORTAOKULU",
  "RİZE - MERKEZ - ÖZEL RİZE BAHÇEŞEHİR KOLEJİ ANADOLU LİSESİ",
  "RİZE - MERKEZ - ÖZEL RİZE BAHÇEŞEHİR KOLEJİ FEN LİSESİ",
  "RİZE - MERKEZ - ÖZEL RİZE BAHÇEŞEHİR KOLEJİ İLKOKULU",
  "RİZE - MERKEZ - ÖZEL RİZE BAHÇEŞEHİR KOLEJİ ORTAOKULU",
  "RİZE - MERKEZ - ÖZEL RİZE ÇÖZÜM ANADOLU LİSESİ",
  "RİZE - MERKEZ - ÖZEL RİZE ÇÖZÜM İLKOKULU",
  "RİZE - MERKEZ - ÖZEL RİZE ÇÖZÜM ORTAOKULU",
  "RİZE - MERKEZ - ÖZEL RİZE POYRAZ ANADOLU LİSESİ",
  "RİZE - MERKEZ - ÖZEL RİZE POYRAZ FEN LİSESİ",
  "RİZE - MERKEZ - ÖZEL RİZE POYRAZ ORTAOKULU",
  "RİZE - MERKEZ - Çiftekavak Polis Amca İlkokulu",
  "RİZE - MERKEZ - Denizciler İlkokulu",
  "RİZE - MERKEZ - Dörtyol Şehit Halil Sadıkoğlu İlkokulu",
  "RİZE - MERKEZ - Elmalı İlkokulu",
  "RİZE - MERKEZ - Gündoğdu 29 Ekim İlkokulu",
  "RİZE - MERKEZ - Hüseyin Yardımcı İlkokulu",
  "RİZE - MERKEZ - İstiklal İlkokulu",
  "RİZE - MERKEZ - Karasu İlkokulu",
  "RİZE - MERKEZ - Kasarcılar İlkokulu",
  "RİZE - MERKEZ - Kendirli Şehit Azim ÖZDEMİR İlkokulu",
  "RİZE - MERKEZ - Küçükçayır İlkokulu",
  "RİZE - MERKEZ - Muradiye İlkokulu",
  "RİZE - MERKEZ - Ömer Halaç İşitme Engelliler İlkokulu",
  "RİZE - MERKEZ - Pazarköy Hafız Ali Usta İlkokulu",
  "RİZE - MERKEZ - Pehlivantaşı İlkokulu",
  "RİZE - MERKEZ - Şehit Nedim ÇALIK İlkokulu",
  "RİZE - MERKEZ - Şevket Yardımcı İlkokulu",
  "RİZE - MERKEZ - Taşköprü Atatürk İlkokulu",
  "RİZE - MERKEZ - Taşlıdere Gazi İlkokulu",
  "RİZE - MERKEZ - Vakıflar İlkokulu",
  "RİZE - MERKEZ - Veliköy Uzun Mustafa Kopuz İlkokulu",
  "RİZE - PAZAR - FUAT ERGENÇ ORTAOKULU",
  "RİZE - PAZAR - Pazar Anadolu İmam Hatip Lisesi",
  "RİZE - PAZAR - Pazar Kız Kulesi Kız Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - PAZAR - Necat Sağbaş Anadolu Lisesi",
  "RİZE - PAZAR - Pazar Fen Lisesi",
  "RİZE - PAZAR - Pazar 10 Mart Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - PAZAR - Pazar Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - PAZAR - Ahmet Tahtakılıç Ortaokulu",
  "RİZE - PAZAR - HAMİDİYE ORTAOKULU",
  "RİZE - PAZAR - VALİ ERDAL ATA ORTAOKULU",
  "RİZE - PAZAR - TOPLU KONUT İDARESİ BAŞKANLIĞI ORTAOKULU",
  "RİZE - PAZAR - Haberal Vakfı Yaşar ve MedineHaberal Ortaokulu",
  "RİZE - PAZAR - AKTEPE ORTAOKULU",
  "RİZE - PAZAR - ATATÜRK ANADOLU LİSESİ",
  "RİZE - PAZAR - Pazar Şehit Murat Naiboğlu Sivil Havacılık Mesleki ve Teknik Anadolu Lisesi",
  "RİZE - PAZAR - Ahmet Mesut Yılmaz İlkokulu",
  "RİZE - PAZAR - AKTEPE İLKOKULU",
  "RİZE - PAZAR - ÖZEL RİZE PAZAR MEKTEBİM İLKOKULU",
  "RİZE - PAZAR - ÖZEL ÇÖZÜM FEN LİSESİ",
  "RİZE - PAZAR - ÖZEL ÇÖZÜM İLKOKULU",
  "RİZE - PAZAR - ÖZEL ÇÖZÜM ORTAOKULU",
  "RİZE - PAZAR - ÖZEL PAZAR AÇI ANADOLU LİSESİ",
  "RİZE - PAZAR - FUAT ERGENÇ İLKOKULU",
  "RİZE - PAZAR - HAMİDİYE İLKOKULU",
  "RİZE - PAZAR - HÜSEYİN SARIOĞLU İLKOKULU",
  "RİZE - PAZAR - TOPLU KONUT İDARESİ BAŞKANLIĞI İLKOKULU",
  "RİZE - PAZAR - VALİ ERDAL ATA İLKOKULU",
  "RİZE - PAZAR - Veysel Vardal İlkokulu",
];

export const MESLEKLER: string[] = [
  "Acil Tıp Teknisyeni",
  "Anaokulu Öğretmeni",
  "Anestezi Teknikeri",
  "Araştırmacı",
  "Asker",
  "Aşçı",
  "Avukat",
  "Bankacı",
  "Beden Eğitimi Öğretmeni",
  "Bilgisayar Mühendisi",
  "Biyomedikal Mühendisi",
  "Bütçe Uzmanı",
  "Çevre Mühendisliği",
  "Çiftçi",
  "Diş Hekimi",
  "Diş Teknisyeni",
  "Diyetisyen",
  "Doktor",
  "Ebe",
  "Eczacı",
  "Eğitmen",
  "Emekli",
  "Ekspresyonist",
  "Elektrik Elektronik Mühendisi",
  "Elektrik Teknisyeni",
  "Emlakçı",
  "Endüstri Mühendisi",
  "Endüstriyel Tasarımcı",
  "Ev Hanımı",
  "Felsefe Öğretmeni",
  "Finans Danışmanı",
  "Fizyoterapist",
  "Fotoğrafçı",
  "Garson",
  "Gazeteci",
  "Gıda Mühendisi",
  "Grafik Tasarımcı",
  "Gümrük Müşaviri",
  "Güvenlik Danışmanı",
  "Güvenlik Görevlisi",
  "Hakim",
  "Harita Mühendisi",
  "Havacılık ve Uzay Mühendisliği",
  "Hemşire",
  "Hostes",
  "Hukukçu (Genel)",
  "İç Mimar",
  "İhracat Uzmanı",
  "İletişim Tasarımcısı",
  "İnsan Kaynakları Uzmanı",
  "İnşaat Mühendisi",
  "İnşaat Teknikeri",
  "İşçi",
  "Jeoloji Mühendisi",
  "Kaptan",
  "Kimya Mühendisi",
  "Kuaför/Berber",
  "Lojistik Uzmanı",
  "Maden Mühendisi",
  "Makine Mühendisi",
  "Makine Teknikeri",
  "Mali Müşavir",
  "Matematik Öğretmeni",
  "Metalurji ve Malzeme Mühendisi",
  "Mimar",
  "Mobilya Ustası",
  "Muhasebeci",
  "Muhasebe Uzmanı",
  "Müfettiş",
  "Müteahhit",
  "Müzisyen",
  "Noter",
  "Öğretmen",
  "Pazarlama Uzmanı",
  "Pilot",
  "Polis",
  "Psikiyatrist",
  "Psikolog",
  "Radyoloji Teknikeri",
  "Reklamcı",
  "Sanat Tarihçisi",
  "Sanat Yönetmeni",
  "Sanatçı",
  "Sekreter/Yönetici Asistanı",
  "Serbest Meslek",
  "Serbest Meslek Altın ve Kuyumculuk",
  "Serbest Meslek Çay İmalatı",
  "Serbest Meslek Elektrikli Ev Aletleri",
  "Serbest Meslek İnşaat",
  "Serbest Meslek Konfeksiyon ve Giyim",
  "Serbest Meslek Mobilya İmalatı ve Satış",
  "Serbest Meslek Otomotiv",
  "Serbest Meslek Sigorta Hizmetleri",
  "Serbest Meslek Tesisatçı",
  "Sistem Analisti",
  "Sınıf Öğretmeni",
  "Sosyal Medya Uzmanı",
  "Sosyolog",
  "Spor Antrenörü",
  "Sporcu",
  "Şef (Restoran)",
  "Şoför",
  "Tarih Öğretmeni",
  "Teknisyen",
  "Tercüman",
  "Terzi",
  "Tiyatro Oyuncusu",
  "Turizm Rehberi",
  "Türk Dili ve Edebiyatı Öğretmeni",
  "Uçak Mühendisi",
  "Veri Bilimcisi",
  "Veteriner",
  "Veteriner Hekimi",
  "Web Geliştiricisi",
  "Yazılımcı",
  "Yazılım Mühendisi",
  "Yönetici",
  "Ziraat Mühendisi",
];

export const SINIFLAR = [8, 9, 10, 11] as const;
